# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c950b6ffb1c72f57d6ee99acaeefffb9cfbaa41a4611ca3cb09390ac9a83b42bea244128731c6e815ad540d4d01011debf4bebc1bbf5f5cb60773557b037f2c

test:
  secret_key_base: 90c6e031c1e7cc0c198de8e1bfdd7568a12e9b52ee9506273218997951bccb8c6b9fdba516a410d8218a1709d93eb5926bb2d0e8e0ae36e4733b6355fdb44a8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
